const i18nDict = {
    zh: {
        nav_diet: "飲食", nav_gym: "訓練", nav_comm: "社群", nav_user: "用戶", nav_settings: "設定",
        nav_today: "今日", nav_7day: "7日規劃", nav_recipe: "食譜庫", nav_today_train: "今日訓練", nav_7day_train: "7日課表", nav_history: "歷史紀錄",
        water_title: "飲水 💧", add_diet: "🍽️ 新增飲食", meal_breakfast: "🌅 早餐", meal_lunch: "☀️ 午餐", meal_dinner: "🌙 晚餐", meal_snack: "🍏 點心",
        btn_save_record: "儲存紀錄", daily_plan_total: "當日規劃總額", edit_plan: "📅 編排", btn_add_list: "加入清單", qty: "份量 / Qty",
        create_recipe: "🥑 建立食譜組合", selected_ingredients: "已選食材", btn_save_recipe: "封裝食譜",
        vol_trend: "近 7 日容量趨勢", workout_log: "🏋️‍♂️ 訓練日誌", strength: "重量訓練", cardio: "有氧運動", weight_kg: "重量(KG)", sets: "組數", reps: "次數", time_mins: "時間(Mins)", distance_km: "距離(KM)", today_list: "今日清單",
        history_query: "📜 歷史紀錄查詢", comm_feed: "動態牆", search_comm: "🔍 搜尋用戶或內容...", my_post: "發佈動態", comm_profile: "個人主頁", comm_desc: "分享您的努力，激勵更多人！", post_type: "貼文類型", upload_media: "點擊上傳相片或短片", btn_publish: "發佈至動態牆", post_placeholder: "今天練得如何？寫下一些心得紀錄吧...", 
        type_diet: "🍱 美味飲食分享", type_training: "💪 訓練動作紀錄", type_physique: "👤 體態轉變", comment_placeholder: "留言...", btn_comment: "發佈", stats_posts: "貼文", stats_followers: "粉絲", stats_following: "追蹤中", my_works: "我的作品與分享",
        user_core: "個人數據核心", curr_weight: "目前體重 (KG)", target_weight: "目標體重 (KG)", gender: "性別", age: "年齡", height: "身高 (CM)", pal: "活動量", btn_sync_data: "同步運算核心數據", ai_target: "AI 建議攝取目標", weight_chart: "體重軌跡", calorie_trend: "熱量攝取趨勢", label_tdee: "維持 TDEE", label_bmi: "身體質量 BMI", label_target_dist: "距目標",
        pal_1_2: "💻 久坐 (辦公族、幾乎不運動)", pal_1_375: "🚶 輕度 (每週輕鬆活動 1-3 天)", pal_1_465: "🏃 中輕度 (每週規律健身 3-4 天)", pal_1_55: "🏃 中度 (每週規律訓練 5-6 天)", pal_1_725: "🏋️ 高度 (每日重訓或勞動力)", pal_1_9: "🔥 極高 (專業運動員、長期競技)", male: "男", female: "女", range_7: "7天", range_30: "30天", range_all: "全部",
        sys_settings: "系統設定", lang_setting: "介面語言 / Language", health_sync: "連接 Apple Health / Fit", health_sync_desc: "自動同步步數與體重", dark_mode: "深色模式", calculating: "計算中...", rest_timer: "休息: 00:00", select_date_cal: "請選擇日曆上的日期",
        legal_support: "法律與支援", privacy_policy: "隱私政策", tos: "服務條款", health_disclaimer: "健康免責聲明", content_mod: "社群內容審核聲明", permissions: "權限導覽", contact_support: "聯繫支援 / 意見回饋", version: "Version 1.0.0 (Build 26)", report_post: "檢舉貼文", block_user: "封鎖用戶"
    },
    en: {
        nav_diet: "Diet", nav_gym: "Gym", nav_comm: "Social", nav_user: "User", nav_settings: "Set",
        nav_today: "Today", nav_7day: "Planner", nav_recipe: "Recipes", nav_today_train: "Workout", nav_7day_train: "Planner", nav_history: "History",
        water_title: "Water 💧", add_diet: "🍽️ Add Meal", meal_breakfast: "🌅 Breakfast", meal_lunch: "☀️ Lunch", meal_dinner: "🌙 Dinner", meal_snack: "🍏 Snack",
        btn_save_record: "Save Record", daily_plan_total: "Daily Plan Total", edit_plan: "📅 Plan", btn_add_list: "Add to List", qty: "Qty",
        create_recipe: "🥑 Create Recipe", selected_ingredients: "Selected", btn_save_recipe: "Save Recipe",
        vol_trend: "7-Day Volume Trend", workout_log: "🏋️‍♂️ Workout Log", strength: "Strength", cardio: "Cardio", weight_kg: "Weight(KG)", sets: "Sets", reps: "Reps", time_mins: "Time(Mins)", distance_km: "Distance(KM)", today_list: "Today's List",
        history_query: "📜 History", comm_feed: "Feed", search_comm: "🔍 Search users or posts...", my_post: "Create Post", comm_profile: "Profile", comm_desc: "Share your progress!", post_type: "Post Type", upload_media: "Upload Photo/Video", btn_publish: "Publish to Feed", post_placeholder: "How was your workout today? Write a log...",
        type_diet: "🍱 Diet Share", type_training: "💪 Training Log", type_physique: "👤 Physique Update", comment_placeholder: "Add a comment...", btn_comment: "Post", stats_posts: "Posts", stats_followers: "Followers", stats_following: "Following", my_works: "My Posts & Media",
        user_core: "Core Data", curr_weight: "Current Wt (KG)", target_weight: "Target Wt (KG)", gender: "Gender", age: "Age", height: "Height (CM)", pal: "Activity Level", btn_sync_data: "Sync Core Data", ai_target: "AI Calorie Goal", weight_chart: "Weight Tracker", calorie_trend: "Calorie Trend", label_tdee: "Maint. TDEE", label_bmi: "Body Mass BMI", label_target_dist: "To Target",
        pal_1_2: "💻 Sedentary (Office job)", pal_1_375: "🚶 Light (Exercise 1-3 days/wk)", pal_1_465: "🏃 Mod-Light (3-4 days/wk)", pal_1_55: "🏃 Moderate (5-6 days/wk)", pal_1_725: "🏋️ Heavy (Daily hard training/labor)", pal_1_9: "🔥 Extreme (Pro athlete)", male: "Male", female: "Female", range_7: "7 Days", range_30: "30 Days", range_all: "All",
        sys_settings: "System Settings", lang_setting: "Language", health_sync: "Connect Health/Fit", health_sync_desc: "Auto-sync steps & weight", dark_mode: "Dark Mode", calculating: "Calc...", rest_timer: "Rest: 00:00", select_date_cal: "Please select a date",
        legal_support: "Legal & Support", privacy_policy: "Privacy Policy", tos: "Terms of Service", health_disclaimer: "Health Disclaimer", content_mod: "Content Moderation", permissions: "Permissions", contact_support: "Contact Support / Feedback", version: "Version 1.0.0 (Build 26)", report_post: "Report Post", block_user: "Block User"
    }
};

const dayLabels = {
    zh: { '週一':'週一', '週二':'週二', '週三':'週三', '週四':'週四', '週五':'週五', '週六':'週六', '週日':'週日' },
    en: { '週一':'Mon', '週二':'Tue', '週三':'Wed', '週四':'Thu', '週五':'Fri', '週六':'Sat', '週日':'Sun' }
};

const baseDB = [
    {name:"白飯 (White Rice/碗/200g)",p:5,c:56,f:0.6}, {name:"糙米飯 (Brown Rice/碗/200g)",p:5,c:52,f:1.6}, {name:"地瓜 (Sweet Potato/150g)",p:2,c:36,f:0.3}, {name:"馬鈴薯 (Potato/150g)",p:3,c:26,f:0.2}, {name:"全麥吐司 (Whole Wheat Toast/片)",p:4,c:15,f:1}, {name:"白吐司 (White Toast/片)",p:3,c:14,f:1}, {name:"燕麥片 (Oats/50g)",p:6,c:33,f:3.5}, {name:"義大利麵 (Pasta/100g乾)",p:12,c:75,f:1.5}, {name:"玉米 (Corn/根)",p:4,c:25,f:1.5}, {name:"烏龍麵 (Udon/200g)",p:5,c:45,f:1},
    {name:"雞胸肉 (Chicken Breast/100g)",p:31,c:0,f:3.6}, {name:"雞腿肉 (Chicken Thigh/100g/去皮)",p:24,c:0,f:8}, {name:"雞蛋 (Egg/顆)",p:7,c:0.6,f:5}, {name:"豬里肌 (Pork Loin/100g)",p:22,c:0,f:4}, {name:"豬梅花 (Pork Shoulder/100g)",p:18,c:0,f:17}, {name:"牛腱 (Beef Shank/100g)",p:26,c:0,f:4}, {name:"牛小排 (Short Rib/100g)",p:15,c:0,f:28}, {name:"培根 (Bacon/片)",p:3,c:0.5,f:10}, {name:"鴨肉 (Duck/100g)",p:18,c:0,f:15}, {name:"羊肉 (Lamb/100g)",p:20,c:0,f:12},
    {name:"鯛魚片 (Tilapia/100g)",p:18,c:0,f:1.5}, {name:"鮭魚 (Salmon/100g)",p:20,c:0,f:14}, {name:"鱈魚 (Cod/100g)",p:16,c:0,f:1}, {name:"蝦子 (Shrimp/100g)",p:21,c:1,f:1}, {name:"蛤蜊 (Clam/100g肉)",p:13,c:3,f:0.6}, {name:"小卷 (Squid/100g)",p:16,c:1,f:1}, {name:"鮪魚罐頭 (Canned Tuna/水煮/100g)",p:24,c:0,f:0.8}, {name:"蟹肉棒 (Crab Stick/5條)",p:6,c:10,f:0.5}, {name:"生蠔 (Oyster/100g)",p:9,c:5,f:2}, {name:"鯖魚 (Mackerel/100g)",p:19,c:0,f:18},
    {name:"嫩豆腐 (Silken Tofu/半盒/150g)",p:7,c:3,f:4}, {name:"板豆腐 (Firm Tofu/100g)",p:9,c:2,f:5}, {name:"無糖豆漿 (Unsweetened Soy Milk/400ml)",p:13,c:4,f:8}, {name:"低脂牛奶 (Low-fat Milk/240ml)",p:8,c:12,f:3}, {name:"全脂牛奶 (Whole Milk/240ml)",p:8,c:12,f:8}, {name:"希臘優格 (Greek Yogurt/100g)",p:10,c:4,f:0.5}, {name:"起司片 (Cheese Slice/片)",p:5,c:1,f:6}, {name:"起司條 (String Cheese/條)",p:7,c:1,f:5}, {name:"豆干(Dried Tofu/2塊)",p:10,c:2,f:6}, {name:"納豆(Natto/盒)",p:7,c:5,f:4}, {name:"毛豆(Edamame/100g)",p:12,c:10,f:5},
    {name:"青江菜(Bok Choy/100g)",p:1.5,c:2,f:0.2}, {name:"高麗菜(Cabbage/100g)",p:1.3,c:5,f:0.2}, {name:"花椰菜(Cauliflower/100g)",p:3,c:5,f:0.4}, {name:"菠菜(Spinach/100g)",p:2.5,c:3,f:0.4}, {name:"空心菜(Water Spinach/100g)",p:2,c:3,f:0.3}, {name:"大白菜(Napa Cabbage/100g)",p:1,c:3,f:0.1}, {name:"洋蔥(Onion/100g)",p:1,c:9,f:0.1}, {name:"胡蘿蔔(Carrot/100g)",p:1,c:9,f:0.2}, {name:"小黃瓜(Cucumber/100g)",p:1,c:3,f:0.1}, {name:"番茄(Tomato/中顆)",p:1,c:4,f:0.2},
    {name:"香菇(Shiitake Mushroom/100g)",p:3,c:4,f:0.3}, {name:"金針菇(Enoki Mushroom/100g)",p:2.5,c:6,f:0.4}, {name:"杏鮑菇(King Oyster Mushroom/100g)",p:2.5,c:5,f:0.3}, {name:"苦瓜(Bitter Melon/100g)",p:1,c:4,f:0.1}, {name:"茄子(Eggplant/100g)",p:1,c:6,f:0.2}, {name:"青椒(Green Pepper/100g)",p:1,c:5,f:0.2}, {name:"竹筍(Bamboo Shoot/100g)",p:2,c:4,f:0.2}, {name:"蘆筍(Asparagus/100g)",p:2.2,c:4,f:0.2}, {name:"南瓜(Pumpkin/100g)",p:1.7,c:15,f:0.2}, {name:"冬瓜(Winter Melon/100g)",p:0.5,c:2,f:0.1},
    {name:"香蕉(Banana/根)",p:1.1,c:27,f:0.3}, {name:"蘋果(Apple/中顆)",p:0.5,c:25,f:0.4}, {name:"奇異果(Kiwi/顆)",p:1,c:15,f:0.5}, {name:"芭樂(Guava/中顆)",p:2,c:24,f:0.7}, {name:"葡萄(Grape/10顆)",p:0.5,c:15,f:0.2}, {name:"柳丁(Orange/顆)",p:1,c:12,f:0.2}, {name:"木瓜(Papaya/1/4個)",p:1,c:15,f:0.2}, {name:"西瓜(Watermelon/片)",p:1,c:12,f:0.2}, {name:"鳳梨(Pineapple/100g)",p:0.5,c:13,f:0.1}, {name:"草莓(Strawberry/10顆)",p:0.7,c:8,f:0.3},
    {name:"火龍果(Dragon Fruit/100g)",p:1,c:12,f:0.5}, {name:"酪梨(Avocado/100g)",p:2,c:8,f:15}, {name:"藍莓(Blueberry/100g)",p:0.7,c:14,f:0.3}, {name:"芒果(Mango/100g)",p:0.6,c:15,f:0.4}, {name:"櫻桃(Cherry/10顆)",p:1,c:12,f:0.3},
    {name:"綜合堅果(Mixed Nuts/20g)",p:4,c:4,f:11}, {name:"花生(Peanut/20g)",p:5,c:3,f:10}, {name:"腰果(Cashew/20g)",p:4,c:6,f:9}, {name:"黑巧克力(Dark Choc 85%/20g)",p:2,c:4,f:10}, {name:"蘇打餅乾(Soda Cracker/3片)",p:2,c:15,f:3}, {name:"紅豆湯(Red Bean Soup/碗)",p:6,c:40,f:1}, {name:"茶葉蛋(Tea Egg/顆)",p:7,c:1,f:5}, {name:"地瓜球(Sweet Potato Ball/10顆)",p:1,c:45,f:15}, {name:"雞蛋糕(Egg Cake/5個)",p:4,c:30,f:6}, {name:"爆米花(Popcorn/小份)",p:3,c:30,f:12},
    {name:"黑咖啡(Black Coffee/大杯)",p:0.5,c:1,f:0}, {name:"無糖綠茶(Green Tea/500ml)",p:0,c:0,f:0}, {name:"拿鐵(Latte/無糖/大杯)",p:10,c:15,f:10}, {name:"珍珠奶茶(Boba Tea/微糖/700ml)",p:5,c:80,f:25}, {name:"可樂(Cola/罐)",p:0,c:35,f:0}, {name:"柳橙汁(Orange Juice/200ml)",p:1,c:22,f:0.2}, {name:"乳清蛋白粉(Whey Protein/份)",p:20,c:3,f:1.5}, {name:"啤酒(Beer/罐)",p:1,c:13,f:0}, {name:"紅酒(Red Wine/杯)",p:0,c:4,f:0}, {name:"運動飲料(Sports Drink/罐)",p:0,c:25,f:0},
    {name:"麥香雞(McChicken/個)",p:15,c:40,f:18}, {name:"大麥克(Big Mac/個)",p:25,c:45,f:30}, {name:"麥脆雞(Fried Chicken/塊)",p:18,c:15,f:25}, {name:"薯條(French Fries/中)",p:3,c:40,f:15}, {name:"牛肉麵(Beef Noodle Soup/碗)",p:30,c:65,f:20}, {name:"魯肉飯(Braised Pork Rice/碗)",p:10,c:50,f:25}, {name:"水餃(Dumplings/10顆)",p:15,c:55,f:20}, {name:"鍋貼(Pan-fried Dumplings/10顆)",p:18,c:60,f:35}, {name:"便利商店便當(Bento Box/個)",p:25,c:90,f:20}, {name:"三明治(Sandwich/個)",p:12,c:30,f:10},
    {name:"珍珠奶茶(Boba Tea/全糖/700ml)",p:5,c:105,f:25}, {name:"無糖烏龍茶(Oolong Tea/500ml)",p:0,c:0,f:0}, {name:"燕麥奶(Oat Milk/250ml)",p:3,c:16,f:5}, {name:"杏仁奶(Almond Milk/250ml)",p:1,c:1,f:2.5}, {name:"豆漿(Soy Milk/有糖/400ml)",p:13,c:20,f:8}, {name:"美式咖啡(Americano/熱)",p:0,c:1,f:0}, {name:"蘋果汁(Apple Juice/200ml)",p:0.2,c:23,f:0.1}, {name:"葡萄汁(Grape Juice/200ml)",p:0.5,c:30,f:0.1}, {name:"冬瓜茶(Winter Melon Tea/500ml)",p:0,c:35,f:0}, {name:"多多綠茶(Yakult Green Tea/500ml)",p:2,c:40,f:0},
    {name:"蛋塔(Egg Tart/個)",p:3,c:20,f:15}, {name:"車輪餅(Wheel Pie/奶油)",p:4,c:30,f:10}, {name:"車輪餅(Wheel Pie/紅豆)",p:5,c:35,f:8}, {name:"蔥抓餅(Scallion Pancake/加蛋)",p:12,c:45,f:25}, {name:"雞排(Fried Chicken Fillet/大片)",p:35,c:40,f:32}, {name:"甜不辣(Tempura/炸/份)",p:6,c:35,f:18}, {name:"豬血糕(Pig Blood Cake/支)",p:4,c:30,f:1}, {name:"滷豆干(Braised Tofu/份)",p:14,c:5,f:8}, {name:"滷海帶(Braised Kelp/份)",p:1,c:3,f:0}, {name:"滷百頁豆腐(Braised Tofu/份)",p:18,c:5,f:20},
    {name:"披薩(Pizza/夏威夷/片)",p:12,c:30,f:15}, {name:"炸雞腿(Fried Chicken Leg/支)",p:20,c:12,f:18}, {name:"炸薯餅(Hash Brown/塊)",p:1,c:15,f:10}, {name:"起司漢堡(Cheeseburger/個)",p:15,c:30,f:15}, {name:"潛艇堡(Sub/牛肉6吋)",p:25,c:45,f:10}, {name:"潛艇堡(Sub/香烤雞胸6吋)",p:22,c:45,f:5}, {name:"大腸麵線(Oyster Vermicelli/碗)",p:10,c:45,f:15}, {name:"臭豆腐(Stinky Tofu/碗)",p:12,c:20,f:18}, {name:"蚵仔煎(Oyster Omelet/份)",p:14,c:40,f:22}, {name:"肉圓(Ba-wan/顆)",p:6,c:40,f:10},
    {name:"排骨飯(Pork Chop Bento/便當)",p:32,c:95,f:35}, {name:"雞腿便當(Chicken Leg Bento/炸)",p:35,c:90,f:40}, {name:"控肉飯(Braised Pork Bento/便當)",p:25,c:90,f:45}, {name:"肉絲炒飯(Pork Fried Rice/份)",p:18,c:85,f:25}, {name:"炒麵(Fried Noodles/份)",p:15,c:80,f:22}, {name:"義大利麵(Pasta/白醬培根)",p:20,c:85,f:40}, {name:"義大利麵(Pasta/紅醬肉醬)",p:22,c:85,f:25}, {name:"義大利麵(Pasta/青醬雞肉)",p:28,c:80,f:35}, {name:"鐵板麵(Teppanyaki Noodles/份)",p:10,c:60,f:15}, {name:"廣東粥(Cantonese Congee/碗)",p:8,c:55,f:5},
    {name:"雪花牛(Beef Slices/火鍋肉/100g)",p:14,c:0,f:40}, {name:"梅花豬(Pork Slices/火鍋肉/100g)",p:18,c:0,f:15}, {name:"松阪豬(Matsusaka Pork/100g)",p:18,c:0,f:12}, {name:"雞柳條(Chicken Tenders/100g)",p:22,c:0,f:1.5}, {name:"鯛魚下巴(Tilapia Jaw/100g)",p:15,c:0,f:18}, {name:"鮭魚肚(Salmon Belly/100g)",p:16,c:0,f:25}, {name:"魷魚圈(Calamari/100g)",p:15,c:2,f:1}, {name:"蛤蠣(Clams/100g去殼)",p:10,c:2,f:1}, {name:"牡蠣(Oysters/100g)",p:9,c:5,f:2}, {name:"蝦仁(Shrimp/100g)",p:20,c:0,f:1},
    {name:"高麗菜(Fried Cabbage/炒/100g)",p:1.5,c:5,f:5}, {name:"菠菜(Fried Spinach/炒/100g)",p:2.5,c:4,f:5}, {name:"地瓜葉(Boiled Yam Leaves/燙/100g)",p:3,c:4,f:1}, {name:"芥藍菜(Chinese Broccoli/100g)",p:2,c:4,f:0}, {name:"龍鬚菜(Chayote Shoots/100g)",p:3,c:5,f:0}, {name:"空心菜(Fried Water Spinach/炒/100g)",p:2,c:3,f:5}, {name:"大陸妹(Boiled Lettuce/燙/100g)",p:1.5,c:3,f:1}, {name:"白花椰菜(White Cauliflower/100g)",p:2,c:5,f:0}, {name:"青花菜(Broccoli/水煮/100g)",p:3,c:6,f:0}, {name:"綜合菇(Mixed Mushrooms/炒/100g)",p:3,c:5,f:4},
    {name:"鮭魚握壽司(Salmon Sushi/2貫)",p:8,c:15,f:5}, {name:"鮪魚握壽司(Tuna Sushi/2貫)",p:10,c:15,f:1}, {name:"玉子燒壽司(Tamagoyaki Sushi/2貫)",p:5,c:16,f:3}, {name:"稻荷壽司(Inari Sushi/豆皮/2貫)",p:4,c:20,f:6}, {name:"花壽司(Maki Sushi/4片)",p:6,c:30,f:4}, {name:"炸豬排丼(Katsudon/份)",p:35,c:100,f:30}, {name:"牛丼(Gyudon/份)",p:25,c:95,f:25}, {name:"親子丼(Oyakodon/份)",p:30,c:90,f:15}, {name:"炸蝦天婦羅(Shrimp Tempura/2尾)",p:10,c:20,f:12}, {name:"烏龍湯麵(Udon Noodle Soup/碗)",p:12,c:70,f:5},
    {name:"水煮鮪魚罐頭(Tuna in Water/半罐)",p:12,c:0,f:0.5}, {name:"油漬鮪魚罐頭(Tuna in Oil/半罐)",p:12,c:0,f:8}, {name:"鯖魚罐頭(Mackerel Canned/半罐)",p:14,c:2,f:12}, {name:"蒲燒鰻罐頭(Eel Canned/半罐)",p:10,c:8,f:10}, {name:"玉米粒罐頭(Corn Canned/100g)",p:3,c:20,f:1}, {name:"黑豆(Black Beans/熟/50g)",p:8,c:15,f:4}, {name:"鷹嘴豆(Chickpeas/熟/50g)",p:4,c:14,f:1}, {name:"綠豆湯(Mung Bean Soup/碗)",p:6,c:35,f:0}, {name:"紅豆冰棒(Red Bean Popsicle/支)",p:2,c:25,f:2}, {name:"薏仁湯(Job's Tears Soup/碗)",p:4,c:30,f:1},
    {name:"芋圓(Taro Balls/10顆)",p:1,c:35,f:8}, {name:"燒仙草(Hot Grass Jelly/碗)",p:2,c:25,f:0}, {name:"豆花(Tofu Pudding/碗/無糖水)",p:8,c:5,f:4}, {name:"布丁(Pudding/盒)",p:4,c:20,f:5}, {name:"優酪乳(Yogurt Drink/原味/200ml)",p:6,c:24,f:2}, {name:"水餃(Dumplings/鮮肉/10顆)",p:15,c:50,f:22}, {name:"水煎包(Pan-fried Bun/份)",p:8,c:45,f:20}, {name:"小籠包(Soup Dumpling/顆)",p:4,c:15,f:6}, {name:"蘿蔔糕(Turnip Cake/片)",p:2,c:20,f:5}, {name:"蛋餅(Egg Pancake/原味)",p:8,c:30,f:12},
    {name:"黑糖珍珠(Brown Sugar Boba/50g)",p:0,c:40,f:0}, {name:"仙草凍(Grass Jelly/100g)",p:0,c:5,f:0}, {name:"愛玉(Aiyu Jelly/100g)",p:0,c:1,f:0}, {name:"蒟蒻(Konjac/100g)",p:0,c:4,f:0}, {name:"椰果(Coconut Jelly/50g)",p:0,c:10,f:0}, {name:"粉條(Tapioca Noodles/50g)",p:0,c:15,f:0}, {name:"湯圓(Tangyuan/50g)",p:1,c:35,f:1}, {name:"地瓜圓(Sweet Potato Balls/50g)",p:1,c:30,f:1}, {name:"麻糬(Mochi/花生/顆)",p:3,c:25,f:8}, {name:"麻糬(Mochi/芝麻/顆)",p:3,c:25,f:9},
    {name:"肋眼牛排 (Ribeye Steak/100g)",p:24,c:0,f:14}, {name:"火雞胸肉 (Turkey Breast/100g)",p:29,c:0,f:1}, {name:"貝果 (Bagel/個)",p:10,c:48,f:1.5}, {name:"酸種麵包 (Sourdough Bread/片)",p:4,c:18,f:1}, {name:"美式鬆餅 (Pancakes/2片)",p:6,c:30,f:8}, {name:"格子鬆餅 (Waffles/片)",p:4,c:25,f:10}, {name:"燕麥粥 (Oatmeal/碗)",p:6,c:27,f:3}, {name:"起司通心粉 (Mac & Cheese/碗)",p:12,c:45,f:10}, {name:"茅屋起司 (Cottage Cheese/100g)",p:11,c:3,f:4}, {name:"莫札瑞拉起司 (Mozzarella/30g)",p:6,c:1,f:6},
    {name:"切達起司 (Cheddar/30g)",p:7,c:0.5,f:9}, {name:"鷹嘴豆泥 (Hummus/2匙)",p:2,c:4,f:5}, {name:"花生醬 (Peanut Butter/2匙)",p:7,c:6,f:16}, {name:"杏仁醬 (Almond Butter/2匙)",p:7,c:6,f:18}, {name:"薩拉米香腸 (Salami/30g)",p:6,c:1,f:11}, {name:"酪梨吐司 (Avocado Toast/片)",p:6,c:20,f:12}, {name:"凱薩沙拉 (Caesar Salad/碗)",p:5,c:10,f:15}, {name:"馬鈴薯泥 (Mashed Potatoes/碗)",p:4,c:35,f:8}, {name:"英式烤豆 (Baked Beans/碗)",p:12,c:40,f:1}, {name:"藜麥 (Quinoa/煮熟1碗)",p:8,c:39,f:3.5}, 
    {name:"櫛瓜 (Zucchini/100g)",p:1,c:3,f:0}, {name:"抱子甘藍 (Brussels Sprouts/100g)",p:3,c:9,f:0}, {name:"藍莓 (Blueberries/碗)",p:1,c:21,f:0.5}, {name:"覆盆子 (Raspberries/碗)",p:1.5,c:15,f:0.8}, {name:"燕麥穀物 (Granola/半碗)",p:5,c:30,f:10}, {name:"可頌 (Croissant/個)",p:5,c:26,f:12}, {name:"瑪芬蛋糕 (Muffin/個)",p:6,c:50,f:15}, {name:"甜甜圈 (Donut/個)",p:4,c:30,f:15}, {name:"熱狗 (Hot Dog/份)",p:10,c:20,f:15}, {name:"義大利臘腸披薩 (Pepperoni Pizza/片)",p:12,c:35,f:15}, 
    {name:"麥克雞塊 (Chicken Nuggets/6塊)",p:15,c:15,f:18}, {name:"美式炒蛋 (Scrambled Eggs/2顆)",p:12,c:2,f:14}, {name:"歐姆蛋 (Omelet/起司口味)",p:16,c:3,f:20}, {name:"雞肉捲餅 (Chicken Wrap/份)",p:25,c:40,f:12}, {name:"墨西哥捲餅 (Burrito/份)",p:20,c:50,f:18}, {name:"塔可餅 (Taco/雞肉)",p:15,c:20,f:10}, {name:"炸魚薯條 (Fish and Chips/份)",p:25,c:60,f:30}, {name:"豬排 (Pork Chop/100g)",p:25,c:0,f:12}, {name:"烤牛肉 (Roast Beef/100g)",p:26,c:0,f:10}, {name:"義式肉丸 (Meatballs/5顆)",p:15,c:10,f:18}, 
    {name:"番茄肉醬義大利麵 (Spaghetti Bolognese)",p:20,c:65,f:15}, {name:"千層麵 (Lasagna/份)",p:22,c:50,f:20}, {name:"蛤蜊巧達湯 (Clam Chowder/碗)",p:8,c:20,f:12}, {name:"番茄濃湯 (Tomato Soup/碗)",p:2,c:15,f:4}
];

const gymDB = ["槓鈴臥推 (Barbell Bench Press)", "啞鈴臥推 (Dumbbell Bench Press)", "上胸臥推 (Incline Bench Press)", "下胸臥推 (Decline Bench Press)", "機械飛鳥 (Machine Fly)", "滑輪下拉 (Lat Pulldown)", "引體向上 (Pull-up)", "槓鈴划船 (Barbell Row)", "啞鈴划船 (Dumbbell Row)", "坐姿划船 (Seated Row)", "槓鈴深蹲 (Barbell Squat)", "頸前深蹲 (Front Squat)", "硬舉 (Deadlift)", "腿推舉 (Leg Press)", "羅馬尼亞硬舉 (Romanian Deadlift)", "保加利亞分腿蹲 (Bulgarian Split Squat)", "腿彎舉 (Leg Curl)", "腿伸直 (Leg Extension)", "槓鈴肩推 (Barbell Shoulder Press)", "啞鈴肩推 (Dumbbell Shoulder Press)", "側平舉 (Lateral Raise)", "前平舉 (Front Raise)", "滑輪側平舉 (Cable Lateral Raise)", "反向飛鳥 (Reverse Fly)", "二頭彎舉 (Bicep Curl)", "錘式彎舉 (Hammer Curl)", "三頭下壓 (Tricep Pushdown)", "法式彎舉 (Skull Crusher)", "仰臥起坐 (Sit-up)", "棒式 (Plank)", "捲腹 (Crunch)", "俄羅斯轉體 (Russian Twist)", "波比跳 (Burpee)", "羅馬椅挺身 (Hyperextension)", 
"滑輪夾胸 (Cable Crossover)", "滑輪面拉 (Face Pull)", "滑輪單臂划船 (Single-arm Cable Row)", "滑輪飛鳥 (Cable Fly)", "滑輪過頭三頭伸展 (Overhead Tricep Extension)", "滑輪直臂下拉 (Straight-arm Pulldown)", 
"壺鈴擺盪 (Kettlebell Swing)", "壺鈴深蹲 (Kettlebell Squat)", "壺鈴土耳其起立 (Turkish Get-up)", "壺鈴肩推 (Kettlebell Press)", "壺鈴高腳杯深蹲 (Goblet Squat)", "壺鈴農夫走路 (Farmer's Walk)", "壺鈴單臂划船 (Single-arm KB Row)", "壺鈴硬舉 (Kettlebell Deadlift)"];

const cardioDB = ["跑步 (Running)", "自行車 (Cycling)", "游泳 (Swimming)", "橢圓機 (Elliptical)", "划船機 (Rowing Machine)", "階梯機 (Stair Climber)", "跳繩 (Jump Rope)", "有氧操 (Aerobics)", "HIIT (High-Intensity Interval Training)"];